
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_training_nov2025'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_training_nov2025'


model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  dbt_training_nov2025:
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: view
      #+materialized: dynamic_table
      #+target_lag: downstream
      #+snowflake_warehouse: COMPUTE_WH
      #+transient: false
      #+enable_iceberg_materialization: True
    gold_airbnb:
      +schema: 'gold_airbnb'
      +materialized: table
    platinum_airbnb:
      +schema: 'platinum_airbnb'
      +materialized: view