dbt_training_nov2025:
  outputs:
    dev:
      account: usmerhj-wg27681
      database: DEV
      password: Shankar@26846479
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: shansnowflake
      warehouse: COMPUTE_WH
    uat:
      account: usmerhj-wg27681
      database: uat
      password: dbtPassword123
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 4
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev