dbt_training_nov2025:
  outputs:
    dev:
      account: usmerhj-wg27681
      database: DEV
      password: dbtPassword123
      role: TRANSFORM1
      schema: BRONZE_AIRBNB
      threads: 54
      type: snowflake
      user: dbttest
      warehouse: COMPUTE_WH
  target: dev
